SET(CMAKE_SYSTEM_NAME Linux)

SET(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
# SET(CMAKE_CXX_COMPILER "")

# where is the target environment
# SET(CMAKE_FIND_ROOT_PATH "")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_EXTRA_C_FLAGS "-Wl,-wrap=malloc -Wl,-wrap=free -Wl,-wrap=calloc")
